@startuml
title 商流取引1
object "Party1" as P1
P1:name = 切り捨て-合計
object "Contract1" as C1
C1:代金丸め = ROUNDDOWN
C1:消費税丸め = ROUNDDOWN
C1:課税単位 = SUM
object "CT1" as CT1
CT1:取引日 = 2013-07-30
object "CE1" as CE1
CE1:量 = 5.5KG
object "CE2" as CE2
CE2:量 = 8.3KG
object "CE7" as CE7
CE7:量 = -5.5KG
object "CE8" as CE8
CE8:量 = 5.0KG
object "CA1" as CA1
CA1:client = 切り捨て-合計
CA1:goods = 鯛のアラ
object "CA2" as CA2
CA2:client = 切り捨て-合計
CA2:goods = ヒラマサのアラ
object "Goods1" as G1
G1:name = 鯛のアラ
G1:price = 276.0円/KG
object "Goods2" as G2
G2:name = ヒラマサのアラ
G2:price = 126.0円/KG
object "課税品目" as I647544261
object "PT9" as PT9
object "PT2" as PT2
object "PT8" as PT8
object "PE13" as PE13
PE13:price = 121.0円
object "PE2" as PE2
PE2:price = 1045.0円
object "PE12" as PE12
PE12:price = 1380.0円
object "PA2" as PA2
PA2:client = 切り捨て-合計
PA2:科目 = 消費税
object "PA1" as PA1
PA1:client = 切り捨て-合計
PA1:科目 = 商品代金
object "消費税" as PAT1073708684
object "商品代金" as PAT75322281
C1 -u-> P1
CT1 -u-> C1
CE1 -l-> CT1
CE1 -r-> CA1
CE2 -l-> CT1
CE2 -r-> CA2
CE7 -l-> CT1
CE7 -r-> CA1
CE8 -l-> CT1
CE8 -r-> CA1
G1 -u-> I647544261
G2 -u-> I647544261
PT9 -u-> CT1
PT2 -u-> CE2
PT8 -u-> CE8
PE13 -l-> PT9
PE13 -r-> PA2
PE2 -l-> PT2
PE2 -r-> PA1
PE12 -l-> PT8
PE12 -r-> PA1
@enduml
