@startuml
title 商流取引2
object "Party2" as P2
P2:name = 切り捨て-明細
object "Contract2" as C2
C2:代金丸め = ROUNDDOWN
C2:消費税丸め = ROUNDDOWN
C2:課税単位 = DETAIL
object "CT2" as CT2
CT2:取引日 = 2013-07-30
object "CE3" as CE3
CE3:量 = 5.5KG
object "CE4" as CE4
CE4:量 = 8.3KG
object "CA3" as CA3
CA3:client = 切り捨て-明細
CA3:goods = 鯛のアラ
object "CA4" as CA4
CA4:client = 切り捨て-明細
CA4:goods = ヒラマサのアラ
object "Goods1" as G1
G1:name = 鯛のアラ
G1:price = 276.0円/KG
object "Goods2" as G2
G2:name = ヒラマサのアラ
G2:price = 126.0円/KG
object "課税品目" as I647544261
object "PT4" as PT4
object "PT5" as PT5
object "PE4" as PE4
PE4:price = 1518.0円
object "PE5" as PE5
PE5:price = 75.0円
object "PE6" as PE6
PE6:price = 1045.0円
object "PE7" as PE7
PE7:price = 52.0円
object "PA3" as PA3
PA3:client = 切り捨て-明細
PA3:科目 = 商品代金
object "PA4" as PA4
PA4:client = 切り捨て-明細
PA4:科目 = 消費税
object "商品代金" as PAT75322281
object "消費税" as PAT1073708684
C2 -u-> P2
CT2 -u-> C2
CE3 -l-> CT2
CE3 -r-> CA3
CE4 -l-> CT2
CE4 -r-> CA4
G1 -u-> I647544261
G2 -u-> I647544261
PT4 -u-> CE3
PT5 -u-> CE4
PE4 -l-> PT4
PE4 -r-> PA3
PE5 -l-> PT4
PE5 -r-> PA4
PE6 -l-> PT5
PE6 -r-> PA3
PE7 -l-> PT5
PE7 -r-> PA4
@enduml
