@startuml
title 商流取引3
object "Party3" as P3
P3:name = 切り捨て-安い方
object "Contract3" as C3
C3:代金丸め = ROUNDDOWN
C3:消費税丸め = ROUNDDOWN
C3:課税単位 = CHEAPER
object "CT3" as CT3
CT3:取引日 = 2013-07-30
object "CE5" as CE5
CE5:量 = 5.5KG
object "CE6" as CE6
CE6:量 = 8.3KG
object "CA5" as CA5
CA5:client = 切り捨て-安い方
CA5:goods = 鯛のアラ
object "CA6" as CA6
CA6:client = 切り捨て-安い方
CA6:goods = ヒラマサのアラ
object "Goods1" as G1
G1:name = 鯛のアラ
G1:price = 276.0円/KG
object "Goods2" as G2
G2:name = ヒラマサのアラ
G2:price = 126.0円/KG
object "課税品目" as I647544261
object "PT6" as PT6
object "PT7" as PT7
object "PE8" as PE8
PE8:price = 1518.0円
object "PE9" as PE9
PE9:price = 75.0円
object "PE10" as PE10
PE10:price = 1045.0円
object "PE11" as PE11
PE11:price = 52.0円
object "PA5" as PA5
PA5:client = 切り捨て-安い方
PA5:科目 = 商品代金
object "PA6" as PA6
PA6:client = 切り捨て-安い方
PA6:科目 = 消費税
object "商品代金" as PAT75322281
object "消費税" as PAT1073708684
C3 -u-> P3
CT3 -u-> C3
CE5 -l-> CT3
CE5 -r-> CA5
CE6 -l-> CT3
CE6 -r-> CA6
G1 -u-> I647544261
G2 -u-> I647544261
PT6 -u-> CE5
PT7 -u-> CE6
PE8 -l-> PT6
PE8 -r-> PA5
PE9 -l-> PT6
PE9 -r-> PA6
PE10 -l-> PT7
PE10 -r-> PA5
PE11 -l-> PT7
PE11 -r-> PA6
@enduml
